version: "3.9"

services:
  my-recipes-book-client-ssr:
    container_name: my-recipes-book-client-ssr
    restart: always
    init: true
    build:
      context: ./
      dockerfile: docker/ssr/Dockerfile
    ports:
      - "8080:4000"
