version: "3.9"

services:
  my-recipes-book-client-prod:
    container_name: my-recipes-book-client-prod
    restart: always
    init: true
    build:
      context: ./
      dockerfile: docker/prod/Dockerfile
    ports:
      - "8080:80"
